name: BillParser CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PDM
        run: pip install pdm

      - name: Install project dependencies
        run: pdm install

      - name: Lint and format check with Ruff
        run: |
          pdm run ruff format --check .
          pdm run ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: ["3.12"]

    environment: TestEnv

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pdm'

      - name: Install PDM
        run: pip install pdm

      - name: Install project dependencies
        run: pdm install

      - name: Run tests and generate coverage report
        env:
          BILLPARSER_PARSERS__PP_OCRv5__TOKEN: ${{ secrets.OCR_TOKEN }}
          BILLPARSER_PARSERS__PP_OCRv5__URL: ${{ secrets.OCR_URL }}
        run: |
          pdm run pytest --cov=billparser --cov-report=xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 1

  upload-coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
