coverage:
  comment:
    layout: "reach,diff,flags,tree"
    behavior: default

  status:
    project:
      default:
        target: 90%
        threshold: 0%

    patch:
      default:
        target: 90%
